= Eclipse

Here is how to configure Eclipse so that it will format your code according to the https://google.github.io/styleguide/javaguide.htm[Google Java Style Guide].

== Format code using the Google Java Style Guide
. Configure the Eclipse formatter: use method 1 or method 2, below
. Apply the newly configured formatter globally or to a specific project: see Vogella’s https://www.vogella.com/tutorials/Eclipse/article.html#code-formatter[tutorial]

== Method 1: Configure Eclipse formatter and tweak Eclipse manually
Download https://github.com/oliviercailloux/Practical-Google-style/blob/master/eclipse-java-google-style%20patched.xml[eclipse-java-google-style patched.xml]. 
Go to Eclipse preferences, `Java` / `Code Style` / `Formatter`, and import that file.

Back to Eclipse preferences, at `Java` / `Code Style` / `Organize Imports`, remove all groups, so that Eclipse will not insert unwanted blank lines within your import blocks.

The Eclipse formatter configuration file provided here is a modified version of Google’s https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml[configuration file for Eclipse].

.Explanation
[%collapsible]
====
I initially downloaded the configuration file provided in Google’s styleguide repository (https://github.com/google/styleguide/blob/505ba68c74eb97e6966f60907ce893001bedc706/eclipse-java-google-style.xml[this version], to be precise), imported it into Eclipse and exported it again so as to adapt its format to recent Eclipse versions, sorted the settings in it (to ease comparisons), then https://github.com/oliviercailloux/Practical-Google-style/compare/c63af7..master#diff-94dbce17ac0d35703ff73ae1f3e30a15235150fa6a7224e0e0bb32b792b4ad70[modified] the file manually. 

* Google Java Style Guide, https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing[3.3.3 Ordering and spacing], requires that static imports come together first in a single block, then a blank line, then non-static imports in a single block. But the related formatter settings (`blank_lines_between_import_groups`, corresponding to `Blank Lines` / `Blank lines within compilation unit` / `Between import groups` in Eclipse formatter configuration GUI) was https://github.com/google/styleguide/issues/273[incorrect] in the original `eclipse-java-google-style.xml` file, so I changed it.
** Also, the Checkstyle configuration file for Google Style Guide (original or mine) requires separator between static and non-static imports (rule https://checkstyle.org/config_imports.html#CustomImportOrder[`CustomImportOrder`], property `separateLineBetweenGroups`), so it is required to correct this in Eclipse’s formatter for compliance with Checkstyle’s requirement.
* Similarly, it is necessary to modify `blank_lines_between_type_declarations` to comply with the style https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace[requirements].
* I enlarged permission to the formatter to split lines (`alignment_for_annotations_on_enum_constant`, `alignment_for_method_declaration`, `alignment_for_parameterized_type_references`, `alignment_for_type_arguments`, `alignment_for_type_parameters`): under the original configuration file, the formatter may leave lines longer than 100 characters where it is actually possible to reformat them; which Google style https://google.github.io/styleguide/javaguide.html#s4.4-column-limit[forbids]. Here is https://github.com/oliviercailloux/JARiS/compare/63a312..72bcba#diff-f20d44cbe9548b0b1617aaa663c17b78dade632ad75548e4844380516224fa8cL128-R130[an example] of a difference this makes.
* `number_of_empty_lines_to_preserve` (configured so as to suppress vertical spacing greater than one blank line) and `blank_lines_after_last_class_body_declaration` (configured so as to suppress blank lines before closing bracket) are personal preferences. This may be subjective, but these settings are compatible with Google style (the first one even https://google.github.io/styleguide/javaguide.html#s4.6.1-vertical-whitespace[encouraged]), and I think they make sense generally.
* There is https://bugs.eclipse.org/bugs/show_bug.cgi?id=471920[no way] (using configuration only) to force Eclipse formatter to satisfy the https://google.github.io/styleguide/javaguide.html#s7.1.2-javadoc-paragraphs[rule] that `<p>` must be immediately followed by a word. Please vote for this bug.
* `Format Java code snippets inside 'pre' tags` disabled because of https://bugs.eclipse.org/bugs/show_bug.cgi?id=552012[Eclipse bug #552012]. Please vote for this bug.

I renamed the file and named the formatter configuration `GoogleStyle patched` to distinguish it from the original one.
====

== Method 2: Configure Eclipse formatter and more
You may instead follow https://github.com/oliviercailloux/java-course/blob/master/Dev%20tools/Eclipse.adoc#configuration[these] instructions, which will add a “GoogleStyle patched” formatter style configured exactly as when following Method 1, and also tweak multiple other aspects of Eclipse.

== Export your settings
Here is how to compare your formatter settings to these ones (or any other ones), assuming you modified them manually using Eclipse’s preference GUI.

* From Eclipse preferences: `Java` / `Code Style` / `Formatter` / `Edit` / `Export…`, save it as `Untitled.xml` (for example)
* Download this repository’s https://github.com/oliviercailloux/Practical-Google-style/blob/master/Sort%20profile%20settings.jsh[Sort profile settings] jshell script
* Run `jshell -R-ea "-R-Dfile=Untitled.xml" --startup "Sort profile settings.jsh"`

You obtain an `Untitled.xml` file with sorted settings elements, which you can then compare using any diff program to other similarly sorted Eclipse formatter configuration files. (It seems to me that Eclipse’s export ordering is not deterministic, hence the sorting step.)

To transform these (or your) settings to the EPF (Eclipse Preference File) format, run `rm out.epf ; jshell -R-ea "-R-Dinput=eclipse-java-google-style patched.xml" --startup "Formatter to EPF.jsh"`.

== References
Some relevant http://www.practicesofmastery.com/post/eclipse-google-java-style-guide/[screenshots]

