= Eclipse
Here is how to configure Eclipse so that it will format your code according to the Google Java Style Guide.

Download https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml[eclipse-java-google-style.xml]. 
Import it in Eclipse (from Eclipse preferences, `Java` / `Code Style` / `Formatter`).

Edit the formatter setting for `Blank Lines` / `Blank lines within compilation unit` / `Between import groups`, set to one blank line. Also (as a matter of personal preference but https://google.github.io/styleguide/javaguide.html#s4.1.3-braces-empty-blocks[compatible] with Google Java Style), I suggest to change: `New Lines` / `Keep braced code on one line` / `Method declaration` to `Never`.

Back to Eclipse preferences, at `Java` / `Code Style` / `Organize Imports`, remove all groups, so that Eclipse will not insert unwanted blank lines within your import blocks.

== Explanation
Google Java Style Guide, https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing[3.3.3 Ordering and spacing], requires that static imports come together first in a single block, then a blank line, then non-static imports in a single block. But the related formatter settings in the `eclipse-java-google-style.xml` file is https://github.com/google/styleguide/issues/273[incorrect].

Also, the Checkstyle configuration file for Google Style Guide, relaxed or not, (correctly) requires separator between static and non-static imports (rule https://checkstyle.org/config_imports.html#CustomImportOrder[`CustomImportOrder`], property `separateLineBetweenGroups`), so if you do not correct this in Eclipse’s formatter, it will be incompatible with Checkstyle’s requirement.

== References
Some relevant http://www.practicesofmastery.com/post/eclipse-google-java-style-guide/[screenshots]

