= Practical Google style

// TODO follow https://github.com/google/google-java-format/issues/646 and https://github.com/google/google-java-format/issues/647 and decide to adopt or document.

Configuration files and practical tips and tricks to configure your Java project so as to apply (a slightly modified version of) the https://google.github.io/styleguide/javaguide.html[Google Java Style Guide].

This repository provides a https://checkstyle.org/[Checkstyle] https://github.com/oliviercailloux/Practical-Google-style/blob/master/Relaxed%20google%20checks.xml[configuration file]; instructions for configuring your (Maven) POM (see below); and an Eclipse formatter https://github.com/oliviercailloux/Practical-Google-style/blob/master/eclipse-java-google-style%20patched.xml[configuration file] together with some https://github.com/oliviercailloux/Practical-Google-style/blob/master/Eclipse.adoc[related instructions].

== Maven
Add the plugin `maven-checkstyle-plugin` to your POM, configured as in https://github.com/oliviercailloux/pom/blob/master/pom.xml#L38-L60[here], in order to fail your build in case of bad formatting. (If put directly into the `build` / `plugins` element instead of the `pluginManagement` element, the check will run https://maven.apache.org/plugins/maven-checkstyle-plugin/usage.html[by default] during the https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference[verify] phase.)

== Checkstyle configuration file
The Checkstyle configuration file provided here is a modified version of their https://github.com/oliviercailloux/Practical-Google-style/blob/original-config/google_checks.xml[configuration file] for Google Style Guide.

.Modifications
[%collapsible]
====
I initially imported the Checkstyle  (from the Checkstyle https://github.com/checkstyle/checkstyle/blob/33fd070957c8a5585479f84a5cb9b35598de8c64/src/main/resources/google_checks.xml[resources]), then https://github.com/oliviercailloux/Practical-Google-style/compare/original-config..master#diff-3ec4477dcb9822e385df285c83b0e83b6d204b89447437359ae2a364f842396a[modified] the file manually. 

* https://checkstyle.org/config_misc.html#Indentation[`braceAdjustment`] disabled because https://github.com/checkstyle/checkstyle/issues/9326[also applies] to braces at the start of a line and after an end of statement, which I do not want.
* Put the global severity level at the Checkstyle default (`error`, instead of `warning` which was explicitly set in the original google checks configuration file), because I consider that the build should fail in case of style error.
** I have however set most of the Javadoc related modules to `warning` severity. The Google Style Guide https://google.github.io/styleguide/javaguide.html#s7.3-javadoc-where-required[requires those checks], but I do not want those to break my build: while developing, I do not insist on having complete and nicely formatted Javadoc, which can be a loss of time when we are still unsure about the definitive form of an API. However, these warnings are relevant when aiming at publishing an API.
* Essentially disabled `https://checkstyle.org/config_javadoc.html#SummaryJavadoc[SummaryJavadoc]`. I kept “forbiddenSummaryFragments” but rendered the summary existence check ineffective with a trick by considering “space” as an end-of-sentence period. As configured originally, this does not correctly implement Google’s requirements, which https://google.github.io/styleguide/javaguide.html#s7.3.4-javadoc-non-required[requests] the summary sentence only for public types. I replaced this with `https://checkstyle.org/config_javadoc.html#JavadocStyle[JavadocStyle]`, which allows for scope configuration and also checks that Javadoc effectively is there.
* Allowed underscores in package names, in violation of the https://checkstyle.sourceforge.io/styleguides/google-java-style-20180523/javaguide.html#s5.2.1-package-names[Google Java Style Guide], thus bringing the pattern closer to the https://checkstyle.sourceforge.io/config_naming.html#PackageName[default one]. Mandating single words makes no sense to me: it prevents applying a https://github.com/oliviercailloux/java-course/blob/master/Best%20practices/Maven.adoc#naming-conventions[systematic strategy] to relate unique package names to Maven (unique) groupIds and artifactIds; and it reduces readability.

I renamed the file to distinguish it from the original style.
====

