= Relaxed google style

A https://checkstyle.org/[Checkstyle] configuration file based on https://google.github.io/styleguide/javaguide.html[Google Java Style Guide], slightly link:#Modifications[modified].

I initially imported the Checkstyle https://github.com/oliviercailloux/Relaxed-google-style/blob/original-config/google_checks.xml[configuration file] for Google Style Guide (from the Checkstyle https://github.com/checkstyle/checkstyle/blob/33fd070957c8a5585479f84a5cb9b35598de8c64/src/main/resources/google_checks.xml[resources]), then modified the file manually. The modifications (details below) aim at “relaxing” the checks, except that I set the global severity level to `error` instead of `warning`.

== Maven
Add the plugin `maven-checkstyle-plugin` to your POM, configured as in https://github.com/oliviercailloux/JARiS/blob/7af1071e4dc8ebfb96371f9afa4db8bc78dd34f9/pom.xml#L19-L41[here], in order to fail your build in case of bad formatting. (The check will run https://maven.apache.org/plugins/maven-checkstyle-plugin/usage.html[by default] during the http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference[verify] phase.)

== Modifications
* Renamed file to distinguish it from the original style
* https://checkstyle.org/config_misc.html#Indentation[`braceAdjustment`] disabled because https://github.com/checkstyle/checkstyle/issues/9326[also applies] to braces at the start of a line and after an end of statement, which I do not want.
* Put the global severity level at `error` (the Checkstyle default) instead of `warning` (which was explicitly set in the original goole checks configuration file), overridden for the following Javadoc related modules: `NonEmptyAtclauseDescription`, `JavadocParagraph`, `MissingJavadocMethod`, `MissingJavadocType`. The Google Style Guide https://google.github.io/styleguide/javaguide.html#s7.3-javadoc-where-required[requires those checks], but I do not want those to break my build: while developing, I do not insist on having complete and nicely formatted Javadoc, which can be a loss of time when we are still unsure about the definitive form of an API. (However, these warnings are relevant when aiming at publishing an API.)

⇒ https://github.com/oliviercailloux/Relaxed-google-style/compare/original-config..master#diff-3ec4477dcb9822e385df285c83b0e83b6d204b89447437359ae2a364f842396a[diff]

== See also
Configure link:Eclipse.adoc[Eclipse]

